// GENERATED by marketing/demo-video/gen-chapters.mjs — do not hand-edit.
// Timings are derived from the segments the edit actually produced, so they
// stay in sync with the footage when the cut changes.

export interface Chapter {
  at: number;
  kicker: string;
  line: string;
  accent?: string;
}

export const MASTER_SECONDS = 80.30;
export const SHORT_SECONDS = 32.27;

export const CHAPTERS: Chapter[] = [
  { at: 0, kicker: "The premise", line: "Don't set a goal.", accent: "Become someone." }, // a1-coldopen
  { at: 9.77, kicker: "Two minutes", line: "An AI coach asks who you're", accent: "becoming." }, // a4-coachopen
  { at: 24.13, kicker: "Your plan, built", line: "Milestones and small daily", accent: "actions." }, // a8-building
  { at: 28.33, kicker: "The daily loop", line: "Two small things.", accent: "That's the day." }, // b1-today
  { at: 35.07, kicker: "Every action counts", line: "Each one is a", accent: "vote." }, // b3-checkoff +1.2s
  { at: 37.37, kicker: "21 days", line: "Not a plan anymore. A", accent: "habit." }, // b4-milestone +1s
  { at: 47.47, kicker: "The payoff", line: "Finish the day, and it", accent: "says so." }, // b5-daycomplete +4.6s
  { at: 55.43, kicker: "No guilt", line: "A missed day never", accent: "erases you." }, // b7-journey
  { at: 67.9, kicker: "It remembers", line: "A coach that reads your", accent: "notes." }, // b9-coachhome +0.3s
  { at: 72.13, kicker: "In your corner", line: "You name a win — it answers,", accent: "personally." }, // b10-exchange +1.5s
];

export const SHORT_CHAPTERS: Chapter[] = [
  { at: 0, kicker: "The premise", line: "Don't set a goal.", accent: "Become someone." }, // s-1
  { at: 3.5, kicker: "Two minutes", line: "Tell an AI coach who you want to", accent: "be." }, // s-2
  { at: 9.87, kicker: "Your plan, built", line: "It writes the", accent: "milestones." }, // s-4
  { at: 12.6, kicker: "The daily loop", line: "Every action is a", accent: "vote." }, // s-5 +0.5s
  { at: 15.1, kicker: "21 days", line: "Not a plan. A", accent: "habit." }, // s-6 +1s
  { at: 18.57, kicker: "The payoff", line: "Finish the day, and it", accent: "says so." }, // s-7 +0.5s
  { at: 21.43, kicker: "No guilt", line: "A missed day never", accent: "erases you." }, // s-8
  { at: 26.8, kicker: "It remembers", line: "A coach in your", accent: "corner." }, // s-9 +1.5s
];
