// GENERATED by marketing/demo-video/gen-chapters.mjs — do not hand-edit.
// Timings are derived from the segments the edit actually produced, so they
// stay in sync with the footage when the cut changes.

export interface Chapter {
  at: number;
  kicker: string;
  line: string;
  accent?: string;
}

export const MASTER_SECONDS = 99.70;
export const SHORT_SECONDS = 35.83;

export const CHAPTERS: Chapter[] = [
  { at: 0, kicker: "The premise", line: "Don't set a goal.", accent: "Become someone." }, // a1-coldopen
  { at: 12.13, kicker: "Two minutes", line: "An AI coach asks who you're", accent: "becoming." }, // a4-coachopen
  { at: 36.57, kicker: "Your plan, built", line: "Milestones and small daily", accent: "actions." }, // a8-building
  { at: 43.8, kicker: "The daily loop", line: "Three small things.", accent: "That's the day." }, // b1-today
  { at: 52.17, kicker: "Every action counts", line: "Each one is a", accent: "vote." }, // b3-checkoff +0.8s
  { at: 55.57, kicker: "21 days", line: "Not a plan anymore. A", accent: "habit." }, // b4-milestone +1.2s
  { at: 64.77, kicker: "The payoff", line: "Finish the day, and it", accent: "says so." }, // b5-daycomplete +2.6s
  { at: 76.73, kicker: "No guilt", line: "A missed day never", accent: "erases you." }, // b7-journey
  { at: 90.2, kicker: "It remembers", line: "A coach that reads your", accent: "notes." }, // b9-coach +1.5s
];

export const SHORT_CHAPTERS: Chapter[] = [
  { at: 0, kicker: "The premise", line: "Don't set a goal.", accent: "Become someone." }, // s-1
  { at: 3.5, kicker: "Two minutes", line: "Tell an AI coach who you want to", accent: "be." }, // s-2
  { at: 10.87, kicker: "Your plan, built", line: "It writes the", accent: "milestones." }, // s-4
  { at: 15.43, kicker: "The daily loop", line: "Every action is a", accent: "vote." }, // s-5 +0.5s
  { at: 18.43, kicker: "21 days", line: "Not a plan. A", accent: "habit." }, // s-6 +1s
  { at: 23.73, kicker: "The payoff", line: "Finish the day, and it", accent: "says so." }, // s-7 +2s
  { at: 27.07, kicker: "No guilt", line: "A missed day never", accent: "erases you." }, // s-8
  { at: 32.33, kicker: "It remembers", line: "A coach in your", accent: "corner." }, // s-9 +1.5s
];
