// GENERATED by marketing/demo-video/gen-iphone-vo.mjs — do not hand-edit.
// Footage-relative subtitle cues for the vertical promo cuts.

export interface Sub {
  start: number;
  end: number;
  text: string;
}

export const SUB_MASTER: Sub[] = [
  { start: 0, end: 3.5, text: "Most habit apps ask what you want to do." },
  { start: 3.6, end: 6.83, text: "This one asks who you want to become." },
  { start: 6.93, end: 9.33, text: "It's a two-minute chat with an AI coach." },
  { start: 9.43, end: 14.03, text: "You tell it your goal — mine was running my first 5K." },
  { start: 14.13, end: 19.13, text: "And it writes you a real plan." },
  { start: 24.53, end: 29.33, text: "Milestones, and a few small daily actions." },
  { start: 29.43, end: 32.13, text: "Each day, you check off a couple of small things." },
  { start: 32.23, end: 34.07, text: "Finish the day, and it says so." },
  { start: 34.17, end: 36.13, text: "Your progress fills in — and never resets." },
  { start: 36.23, end: 41.23, text: "Shape it your way: milestones, dates, how often." },
  { start: 42.43, end: 47.23, text: "Every week, your coach checks in," },
  { start: 47.33, end: 52.33, text: "and remembers what you did." },
  { start: 53.37, end: 56.37, text: "Then it actually coaches you —" },
  { start: 56.47, end: 60.63, text: "adjusting the plan so you don't burn out." },
  { start: 60.73, end: 65.43, text: "Specific, personal, every single week." },
  { start: 65.53, end: 67.77, text: "Not a tracker. Someone in your corner." },
];

export const SUB_SHORT: Sub[] = [
  { start: 0, end: 2.43, text: "This app doesn't ask what you want to do." },
  { start: 2.53, end: 4.17, text: "It asks who you want to become." },
  { start: 4.27, end: 9.27, text: "Tell an AI coach your goal, and it builds a real plan." },
  { start: 9.8, end: 13.37, text: "Milestones and small daily actions." },
  { start: 13.47, end: 15.27, text: "Check off your day —" },
  { start: 15.37, end: 17.57, text: "and it says so." },
  { start: 17.67, end: 19, text: "Each week, your coach checks in." },
  { start: 19.1, end: 21.63, text: "Tell it what's hard," },
  { start: 21.73, end: 25.73, text: "and it adapts the plan to how you're doing." },
];
