// GENERATED by marketing/demo-video/gen-iphone-chapters.mjs — do not hand-edit.
// Side captions for the real-device promo's landscape cuts, derived from the
// segment durations build-iphone*.sh produce.

export interface Chapter {
  at: number;
  kicker: string;
  line: string;
  accent?: string;
}

export const IPHONE_MASTER_SECONDS = 67.77;
export const IPHONE_SHORT_SECONDS = 27.47;

export const IPHONE_CHAPTERS: Chapter[] = [
  { at: 0, kicker: "The premise", line: "Don't set a goal.", accent: "Become someone." }, // i1a
  { at: 3.5, kicker: "Two minutes", line: "An AI coach asks who", accent: "you're becoming." }, // i1b
  { at: 9.43, kicker: "Your plan, written", line: "It turns your goal into", accent: "real habits." }, // i1d +1s
  { at: 25.03, kicker: "Built for you", line: "Milestones and small", accent: "daily actions." }, // i1g +1s
  { at: 30.43, kicker: "The daily loop", line: "Check it off.", accent: "Day complete." }, // i2a +1.5s
  { at: 33.67, kicker: "Your progress", line: "A calendar that fills,", accent: "never resets." }, // i3a
  { at: 35.93, kicker: "Make it yours", line: "Edit milestones and", accent: "target dates." }, // i3b
  { at: 42.33, kicker: "Your coach checks in", line: "“One win from", accent: "last week?”" }, // i4b
  { at: 53.87, kicker: "Real coaching", line: "It adapts the plan to", accent: "how you're doing." }, // i4f +1s
  { at: 60.93, kicker: "In your corner", line: "Specific. Personal.", accent: "Every week." }, // i4h +0.5s
];

export const IPHONE_SHORT_CHAPTERS: Chapter[] = [
  { at: 0, kicker: "Two minutes", line: "Tell an AI coach", accent: "your goal." }, // is1
  { at: 4.57, kicker: "Your plan, written", line: "It becomes", accent: "real habits." }, // is3 +0.8s
  { at: 9.5, kicker: "Built for you", line: "Milestones and daily", accent: "actions." }, // is4
  { at: 14.47, kicker: "The daily loop", line: "Check it off.", accent: "Day complete." }, // is5 +1.5s
  { at: 17.57, kicker: "Your coach", line: "Tell it what's", accent: "hard." }, // is6 +0.2s
  { at: 22.23, kicker: "Real coaching", line: "It adapts to", accent: "how you're doing." }, // is8 +1s
];
